config/routes.rb
Rails.application.routes.draw do
  resources :users 
  get 'users/index2/:id'=>'users#index2'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
#coding:utf-8
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
=begin
   
    (1..12).each do |i|
      User.create(
          :name=>'****',
          :age=>i+30,
          :sex=>'F',
          :home_phone=>'*********',
          :home_address=>'***********'
          )
    end

=end


  end

   def index2
    per_page = params["iDisplayLength"].to_i
    iDisplayStart = params["iDisplayStart"].to_i
    total = User.all.length
    if iDisplayStart!=0
      page = (total/(iDisplayStart*1.0)).ceil
    else
      page = 1
    end
    @users = User.paginate(:page => page,:per_page => per_page).collect{|user|[user.name,user.age,user.sex,user.home_phone,user.home_address]}
    total_records = @users.length
    sEcho = params["sEcho"].to_i
    hash = {'aaData'=> @users,'iTotalRecords'=>total,'iTotalDisplayRecords'=>total,"sEcho"=> sEcho}
    p hash.to_json
    render :json => hash.to_json,:template => false
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :sex, :home_phone, :home_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataTableDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :home_phone %><br>
    <%= f.text_field :home_phone %>
  </div>
  <div class="field">
    <%= f.label :home_address %><br>
    <%= f.text_field :home_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<%#= javascript_include_tag 'jquery.js' %>
<%#= javascript_include_tag 'jquery.dataTables.js' %>
<%#= javascript_include_tag 'jquery.dataTables.min.js' %>
<%#= stylesheet_link_tag 'jquery.dataTables.min'%>
<%#= stylesheet_link_tag 'jquery.dataTables_themeroller'%>
<script>
$(document).ready(function() {
  
    $("#example").dataTable({
      "sPaginationType": "full_numbers",
        "bServerSide": true,
        "bDestroy": false ,
        "sAjaxSource": "/users/index2/1",
        "bProcessing": false,
        /*"sAjaxDataProp": "aData",*/
        
        "bDeferRender":false,
        /*
        "aoColumns": [
            {"mDataProp": 'name'}, //mData 表示发请求时候本列的列明，返回的数据中相同下标名字的数据会填充到这一列
            {"mDataProp": 'age'},
            {"mDataProp": 'home_phone'},
            {"mDataProp": 'home_address'},
            {"sDefaultContent": ''}, // sDefaultContent 如果这一列不需要填充数据用这个属性，值可以不写，起占位作用
            {"sDefaultContent": '', "sClass": "action"}//sClass 表示给本列加class
        ],*/
        "bAutoWidth": true, //自适应宽度
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sProcessing": "正在加载中......",
            "sLengthMenu": "每页显示 _MENU_ 条记录",
            "sZeroRecords": "正在加载中......",
            "sEmptyTable": "表中无数据存在！",
            "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
            "sInfoEmpty": "显示0到0条记录",
            "sInfoFiltered": "数据表中共为 _MAX_ 条记录",
            "sSearch": "搜索",
            "oPaginate": {
                "sFirst": "首页",
                "sPrevious": "上一页",
                "sNext": "下一页",
                "sLast": "末页"
            }
        }
    })
});
</script>
<table id="example">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Home phone</th>
      <th>Home address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td colspan="9"></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<p>
  <strong>Home phone:</strong>
  <%= @user.home_phone %>
</p>

<p>
  <strong>Home address:</strong>
  <%= @user.home_address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>